/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed-variant": "#5a4300",
                "on-surface": "#191c1e",
                "on-primary-fixed": "#2c0051",
                "surface": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "surface-bright": "#ffffff",
                "inverse-on-surface": "#f0f1f3",
                "outline-variant": "#cfc2d6",
                "on-tertiary": "#ffffff",
                "surface-variant": "#e1e2e4",
                "background": "#ffffff",
                "on-surface-variant": "#4d4354",
                "on-tertiary-container": "#fffbff",
                "tertiary-fixed-dim": "#f7be1d",
                "secondary": "#006e2f",
                "secondary-fixed": "#6bff8f",
                "error": "#ba1a1a",
                "error-container": "#ffdad6",
                "on-primary-container": "#fffbff",
                "on-secondary-fixed": "#002109",
                "primary-fixed": "#f0dbff",
                "surface-container": "#edeef0",
                "tertiary-container": "#936f00",
                "primary": "#8127cf",
                "surface-container-highest": "#e1e2e4",
                "primary-container": "#9c48ea",
                "inverse-surface": "#2e3132",
                "on-error-container": "#93000a",
                "on-secondary-container": "#007432",
                "tertiary": "#755800",
                "primary-fixed-dim": "#ddb7ff",
                "inverse-primary": "#ddb7ff",
                "surface-tint": "#842bd2",
                "surface-container-low": "#f3f4f6",
                "on-background": "#191c1e",
                "outline": "#7e7385",
                "secondary-container": "#6bff8f",
                "secondary-fixed-dim": "#4ae176",
                "on-error": "#ffffff",
                "on-primary-fixed-variant": "#6900b3",
                "on-secondary-fixed-variant": "#005321",
                "on-tertiary-fixed": "#251a00",
                "tertiary-fixed": "#ffdf9a",
                "on-primary": "#ffffff",
                "surface-dim": "#d9dadc",
                "on-secondary": "#ffffff",
                "surface-container-high": "#e7e8ea",
                "accent-yellow": "#ffea00",
                "accent-pink": "#ff007f",
                "accent-blue": "#00e5ff"
            },
            borderRadius: {
                "DEFAULT": "0px",
                "lg": "0px",
                "md": "0px",
                "sm": "0px",
                "xl": "0px",
                "full": "0px"
            },
            spacing: {
                "margin-mobile": "16px",
                "border-thin": "2px",
                "border-thick": "4px",
                "unit": "4px",
                "gutter": "24px",
                "margin-desktop": "48px"
            },
            fontFamily: {
                "headline-lg": ["Inter", "sans-serif"],
                "label-mono": ["Space Mono", "monospace"],
                "body-md": ["Inter", "sans-serif"],
                "headline-md": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "headline-lg-mobile": ["Inter", "sans-serif"],
                "headline-xl": ["Inter", "sans-serif"],
                "label-caps": ["Inter", "sans-serif"],
                "sans": ["Inter", "sans-serif"],
                "mono": ["Space Mono", "monospace"],
            },
            fontSize: {
                "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "800"}],
                "label-mono": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "800"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "700"}],
                "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "800"}],
                "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "900"}],
                "label-caps": ["12px", {"lineHeight": "1", "fontWeight": "900", "letterSpacing": "0.1em", "textTransform": "uppercase"}]
            },
            boxShadow: {
                "brutal": "4px 4px 0px 0px rgba(0,0,0,1)",
                "brutal-lg": "8px 8px 0px 0px rgba(0,0,0,1)",
                "brutal-hover": "2px 2px 0px 0px rgba(0,0,0,1)",
            },
            animation: {
                blob: 'blob 7s infinite',
                'fade-in-up': 'fadeInUp 0.5s ease-out forwards',
            },
            keyframes: {
                blob: {
                    '0%': { transform: 'translate(0px, 0px) scale(1)' },
                    '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
                    '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
                    '100%': { transform: 'translate(0px, 0px) scale(1)' },
                },
                fadeInUp: {
                    '0%': { opacity: '0', transform: 'translateY(10px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
            },
        },
    },
    plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
};
